### ISSUE TITLE
Demo link is broken

### ISSUE THREAD

**Issue by afuhrtrumpet** [Kaizhi/polymer-slideshow#2]
Demo link shows "Cannot GET /polymer-slideshow/"

**Comment by shashi** [comment]
Bump!

**Comment by Kaizhi** [comment]
Unfortunately this repo has been dead for a while guys - I wrote this way back when Polymer was first released and it's been too long. I'm sure there's some better examples out there now.

**Comment by shashi** [comment]
`neon-animated-pages` does the trick, really :)
